version: "3.9"

services:
  order-db:
    image: postgres:14
    container_name: order-db
    restart: unless-stopped
    networks:
      - publisher-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderdb
      - TZ=Europe/Zagreb
    ports:
      -  "5433:5432"
    volumes:
      - db:/var/lib/postgres

networks:
  publisher-network:
    name: publisher_net

volumes:
  db:
   driver: local
  