version: "3.9"

services:
  orders-db:
    image: postgres:14
    container_name: orders-db
    restart: unless-stopped
    networks:
      - publisher-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
      - PG_DATA=PG_DATA=/var/lib/postgresql/data/pgdata
      - TZ=Europe/Zagreb
    ports:
      - "5433:5432"
    volumes:
      - orders-db:/var/lib/postgresql/data

networks:
  publisher-network:
    name: publisher_net

volumes:
  orders-db:
    driver: local
  